### ISSUE TITLE
Fix Security Bug in CI File for Uploading Images to ghcr.io Registry

### ISSUE THREAD

**Issue by Unike267** [Unike267/Containers#3]
# Context

As @umarcor taught me, the CI file used to upload images to the `ghcr.io` registry has a security vulnerability.

The methodology I’m currently using is as follows:

```yaml
    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4

      - name: '⛴️ Build container'
        run: podman build -t ghcr.io/unike267/containers/impl-arty - < .github/impl.containerfile

      - name: '🔑 Login to ghcr.io'
        run: echo $REGISTRY_PASSWORD | podman login $IMAGE_REGISTRY -u $REGISTRY_USER --password-stdin
      
      - name: '🛰️ Push image to ghcr.io'
        run: podman push ghcr.io/unike267/containers/impl-arty

      - name: '🔐 Logout of ghcr.io'
        run: podman logout $IMAGE_REGISTRY
```

With this code, if everything works correctly, there isn’t any security issue. However, if the `PUSH` fails for any reason, the `logout` step will not be performed.

To resolve this, we can use the following approach, based on code from the [hdl-containers](https://github.com/hdl/containers) repository:

```yaml
  - name: Release
    uses: pyTooling/Actions/with-post-step@r0
    with:
      main: |
        # Release
        # NOTE: the content of the shell if statement is executed if the command returns 0, thus,
        # the logic of the evaluations in Python is negated.
        if python3 -c 'exit("${{ inputs.skip-release }}".lower() not in ["true","skip","yes"])'; then
            echo "Skipping release..."
            exit 0
        fi
        echo '${{ inputs.gcr_token }}' | docker login gcr.io -u _json_key --password-stdin
        echo '${{ inputs.gh_token }}' | docker login ghcr.io -u gha --password-stdin
        echo '${{ inputs.docker_pass }}' | docker login docker.io -u '${{ inputs.docker_user }}' --password-stdin
        dockerRelease ${{ inputs.architecture }} ${{ inputs.collection }} ${{ inputs.images }}
      post: for registry in gcr.io ghcr.io docker.io; do docker logout "$registry"; done
```

By including a post step, we ensure that the logout will always be executed.

## Related issues:
 
- [gh:docker/login-action #72](https://github.com/docker/login-action/issues/72)

# TO-DO

Fix CI to upload images in a secure way.

---

/cc @umarcor
